#!/bin/bash


function foo
{
	echo "foo"
}

goo()
{
	echo "goo"
}

function hoo()
{
	echo "hoo"
}

foo
goo
hoo


add()
{
	sum=$(($1+$2))
	return $sum
}

add 10 20
echo $?


# 3. 지역변수와 전역변수
test()
{
	msg="hello world"
	local msg1="hellow world1"
}

test

echo $msg
echo $msg1
